/**
 * Frontend mirror of `src/server/shared/permissions/permissions.ts`'s `Permission` union — kept as
 * a type only (no authorization logic) so call sites get autocomplete/typo-checking on the literal
 * strings that already flow through `AuthUser.permissions`. The server's `PERMISSIONS` catalogue
 * remains the single source of truth; update this list whenever that file's keys change.
 */
export type Permission =
  | 'tenant:create'
  | 'tenant:read'
  | 'tenant:update'
  | 'tenant:list:all'
  | 'user:invite'
  | 'user:read:tenant'
  | 'user:role:update'
  | 'user:status:update'
  | 'employee:create'
  | 'employee:read:tenant'
  | 'employee:update'
  | 'employee:read:self'
  | 'employee:update:self'
  | 'attendance:read:tenant'
  | 'attendance:regularization:approve'
  | 'attendance:self'
  | 'attendance:regularization:create'
  | 'leave:read:tenant'
  | 'leave:approve:hr'
  | 'leave:approve:manager'
  | 'leave:apply'
  | 'leave:view:self'
  | 'project:manage'
  | 'task:manage'
  | 'task:view:assigned'
  | 'task:update:own'
  | 'workreport:read:tenant'
  | 'workreport:review'
  | 'workreport:submit'
  | 'timelog:read:tenant'
  | 'timelog:self'
  | 'payroll:manage'
  | 'payroll:read:tenant'
  | 'payslip:read:self'
  | 'recruitment:manage'
  | 'recruitment:read'
  | 'crm:manage'
  | 'crm:read'
  | 'finance:manage'
  | 'finance:read'
  | 'ticket:manage'
  | 'ticket:read:tenant'
  | 'ticket:create'
  | 'ticket:view:self'
  | 'kb:manage'
  | 'kb:read'
  | 'document:manage'
  | 'document:view:self'
  | 'document:upload:self'
  | 'asset:manage'
  | 'roombooking:manage'
  | 'roombooking:create'
  | 'template:manage'
  | 'announcement:manage'
  | 'announcement:read'
  | 'org:manage'
  | 'sop:manage'
  | 'sop:read'
  | 'audit:read'
  | 'dashboard:read:tenant'
  | 'session:manage';
